### ISSUE TITLE
probit link function

### ISSUE THREAD

**Issue by cxy7452** [glm-tools/pyglmnet#159]
Great work!!

Just wondering if there's any plan in implementing the probit link function? We're looking for python glm that supports group lasso with probit link, and it seems that your package is really close to it..!

**Comment by pavanramkumar** [comment]
Hey @cxy7452 thanks for the vote of confidence! Yes, adding more link functions and increasing the capacity to meet what `statsmodels` offers is an important priority.

Right now, we are a bit resource crunched since we are focusing on an 0.1 PyPI release for Oct 31. This will be one of the first features we build for 0.2.

In the mean time, let me know if you'd like to make a pull request yourself and we can work together on it. Thanks!

**Comment by pavanramkumar** [comment]
@cxy7452 we added a probit link here #208

**Comment by jasmainak** [comment]
@pavanramkumar closing issue since this is taken care of
