### ISSUE TITLE
`set_params()` method for aiding warm restarts

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#188]
comparable to: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html#sklearn.linear_model.ElasticNet.set_params

useful for applications like #51

**Comment by jasmainak** [comment]
should we tag some issues for the sprint? Ideally if we tackle one item each day, we can get 10 issues done ...

**Comment by pavanramkumar** [comment]
i'm doing this with the projects feature: https://github.com/glm-tools/pyglmnet/projects/1

**Comment by cxrodgers** [comment]
@pavanramkumar Was this ever implemented? I was thinking about making a simple change in my fork where the GLM.fit method would accept optional `beta0_hat` and `beta_hat` arguments. If provided, they would be used instead of np.random.normal() as the initial fit. Unless it was already implemented somewhere else, I will try to do this in my fork and see how it goes.

**Comment by jasmainak** [comment]
yes, this has been implemented here: https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/base.py#L127. @pavanramkumar should we close this issue?

**Comment by cxrodgers** [comment]
Oh I see, I'm using the pip version, which is older than that. In my version (1.0.0), beta and beta0 are not settable. I'll upgrade.

> In [2]: glm.get_params()
> Out[2]: 
> {'Tau': None,
>  'alpha': 0,
>  'distr': 'poisson',
>  'eta': 4.0,
>  'group': None,
>  'learning_rate': 0.2,
>  'max_iter': 1000000,
>  'random_state': 0,
>  'reg_lambda': [0.00029286445646252375],
>  'score_metric': 'pseudo_R2',
>  'tol': 1e-06,
>  'verbose': False}

**Comment by pavanramkumar** [comment]
Yes it's available from the github version and should make it into the next release. Closing.
